export const ADD_CALULATOR = 'ADD_CALULATOR';
export const SUBTRACT_CALULATOR = 'REMOVE_CALULATOR';
export const MULTIPLY_CALULATOR = 'MULTIPLY_CALULATOR';
export const DEVISION_CALULATOR = 'DIVISION_CALULATOR';